[CmdletBinding()]param(
 [Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$ExpectedCoreDigest,
 [Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$VerificationCapsulePath,
 [Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$IssuingPacketPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$script:n=0
function A([bool]$ok,[string]$m){if(-not$ok){throw "ASSERTION FAILED [$script:n]: $m"};$script:n++}
function Q([string]$text){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.UTF8Encoding]::new($false).GetBytes($text)))}
function K($o,[string]$keys,[string]$m){A ((@($o.PSObject.Properties.Name)-join',')-ceq$keys) $m}
function S([string]$v){$v-cmatch'^[A-F0-9]{64}$'}
$matrix=@'
{"schema":"fleet-exhausted-model-failback-controls.v25","candidate":"opus-model-failback-r27","authority":"ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX","capacity_max_age_seconds":300,"hard_ceiling":100,"execution":{"common":{"effort":"max","turns":12,"wall_seconds":900,"tools":["Read","StructuredOutput"],"result":"route-review-result.v1"},"fable":{"model":"claude-fable-5","role":"coordinator"},"opus":{"model":"claude-opus-5","role":"executor"},"sonnet":{"model":"claude-sonnet-5","role":"verifier"}},"assertions":["INIT_MODEL_EXACT","ROUTE_PACKET_SESSION_EXACT","TERMINAL_REASON_API_ERROR","HTTP_STATUS_429","EXACTLY_ONE_TURN","EXACT_MODEL_SCOPED_RESULT_TEXT","ASSISTANT_ERROR_RATE_LIMIT","ZERO_REVIEW_INPUT_TOKENS","ZERO_REVIEW_OUTPUT_TOKENS","NO_REVIEW_VERDICT_OR_ACCEPTANCE","RATE_LIMIT_EVENTS_COMPLETE_AND_ADJUDICATED","SAME_DOMAIN_CAPACITY_FRESH_SIGNED","CAPACITY_PLUS_ACTIVE_RESERVATIONS_PLUS_CONSERVATIVE_OPUS_ESTIMATE_LTE_100_EVERY_WINDOW","TERMINAL_HASHES_CROSS_BOUND_CLOSE_BEFORE_CLEAR"],"cases":[["exact","none","ELIG"],["wrong_model","model","MODEL"],["generic_429","text","AMBIG"],["error_missing","error","TERM"],["nonterminal","terminal","IDENT"],["verdict_present","credit","CREDIT"],["nonzero_tokens","tokens","TOKENS"],["event_missing","event","CLASS"],["base_rejected","base","ACCOUNT"],["overage_allowed","allowed","OTHER"],["overage_omitted","omitted","OTHER"],["overage_uncorroborated","unsigned","CLASS"],["event_unknown","unknown","CLASS"],["stale_capacity","stale","CAP"],["unsigned_capacity","signature","CAP"],["cross_domain","cross_domain","CAP"],["same_domain_successor","same_domain","ELIG"],["sum_eq100","eq100","ELIG"],["sum_gt100","gt100","CEIL"],["core_reorder","order","CORE"],["core_replace","replace","CORE"],["core_mutated","core_mutated","CORE"],["effort_drift","effort","EXEC"],["bounds_drift","bounds","EXEC"],["identity_drift","identity","EXEC"],["assertion_map","map","MAP"],["open_gate","gate","GATE"],["overlap","overlap","OVERLAP"],["unconsumed_canary","unconsumed","CANARY"],["consumed_canary","consumed","LATER"],["rotation_failure","rotation","ROLLBACK"],["malformed_output","malformed","OUTPUT"],["capsule_unbound","capsule","CAPSULE"],["terminal_fable_carrier_replay","terminal_fable_carrier_replay","REPLAY"],["terminal_binding","terminal_bind","BIND"]],"credit":"NEXT_GATE_ONLY_ZERO_AUTHORITY"}
'@
function E([string]$m){
 $x=[ordered]@{model=1;text=1;assistantError=1;terminalReason=1;credit=0;tokens=0;event='allowed';fresh=1;signed=1;fd='a';cd='a';u5=14;u7=88;r5=0;r7=0;e5=5;e7=5;coreOrder=1;coreReplace=1;coreBytes=1;effortExact=1;boundsExact=1;identityExact=1;map=1;gate='closed';overlap=0;canary='none';rotation=1;output=1;capsule=1;replay=0;packetBind=1;sessionBind=1;terminalBind=1;closeBeforeClear=1}
 switch($m){model{$x.model=0}text{$x.text=0}error{$x.assistantError=0}terminal{$x.terminalReason=0}credit{$x.credit=1}tokens{$x.tokens=1}event{$x.event='missing'}base{$x.event='base'}allowed{$x.event='allowed'}omitted{$x.event='omitted'}unsigned{$x.event='uncorroborated'}unknown{$x.event='unknown'}stale{$x.fresh=0}signature{$x.signed=0}cross_domain{$x.cd='b'}same_domain{$x.fd='b';$x.cd='b'}eq100{$x.u5=90;$x.r5=5;$x.e5=5}gt100{$x.u5=91;$x.r5=5;$x.e5=5}order{$x.coreOrder=0}replace{$x.coreReplace=0}core_mutated{$x.coreBytes=0}effort{$x.effortExact=0}bounds{$x.boundsExact=0}identity{$x.identityExact=0}map{$x.map=0}gate{$x.gate='open'}overlap{$x.overlap=1}unconsumed{$x.canary='unconsumed'}consumed{$x.canary='consumed'}rotation{$x.rotation=0}malformed{$x.output=0}capsule{$x.capsule=0}terminal_fable_carrier_replay{$x.replay=1}terminal_bind{$x.packetBind=0;$x.sessionBind=0;$x.terminalBind=0;$x.closeBeforeClear=0}none{}default{throw "unknown mutation $m"}}
 if(-not$x.model){return 'MODEL'};if(-not$x.text){return 'AMBIG'};if(-not$x.assistantError){return 'TERM'};if(-not$x.terminalReason){return 'IDENT'};if($x.credit){return 'CREDIT'};if($x.tokens){return 'TOKENS'}
 if($x.event-ceq'missing'){return 'CLASS'};if($x.event-ceq'base'){return 'ACCOUNT'};if($x.event-in@('uncorroborated','unknown')){return 'CLASS'};if(-not$x.fresh-or-not$x.signed-or$x.fd-cne$x.cd){return 'CAP'}
 if(($x.u5+$x.r5+$x.e5)-gt100-or($x.u7+$x.r7+$x.e7)-gt100){return 'CEIL'};if(-not$x.coreOrder-or-not$x.coreReplace-or-not$x.coreBytes){return 'CORE'};if(-not$x.effortExact-or-not$x.boundsExact-or-not$x.identityExact){return 'EXEC'};if(-not$x.map){return 'MAP'};if($x.gate-cne'closed'){return 'GATE'};if($x.overlap){return 'OVERLAP'};if($x.canary-ceq'unconsumed'){return 'CANARY'};if(-not$x.rotation){return 'ROLLBACK'};if(-not$x.output){return 'OUTPUT'};if(-not$x.capsule){return 'CAPSULE'};if($x.replay){return 'REPLAY'}
 if(-not$x.packetBind-or-not$x.sessionBind-or-not$x.terminalBind-or-not$x.closeBeforeClear){return 'BIND'};if($x.canary-ceq'consumed'){return 'LATER'};if($m-in@('allowed','omitted')){return 'OTHER'};return 'ELIG'
}
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$s=$matrix|ConvertFrom-Json -Depth 20
K $s 'schema,candidate,authority,capacity_max_age_seconds,hard_ceiling,execution,assertions,cases,credit' 'matrix keys';A ($s.schema-ceq'fleet-exhausted-model-failback-controls.v25'-and$s.candidate-ceq'opus-model-failback-r27') 'matrix identity';A ($s.capacity_max_age_seconds-eq300-and$s.hard_ceiling-eq100) 'limits';A ($s.assertions.Count-eq14-and@($s.assertions|Sort-Object -Unique).Count-eq14) 'assertions';A ($s.cases.Count-eq35-and@($s.cases|ForEach-Object{$_[0]}|Sort-Object -Unique).Count-eq35) '35 unique cases'
A ($s.execution.common.effort-ceq'max'-and$s.execution.common.turns-eq12-and$s.execution.common.wall_seconds-eq900) 'bounds';A ((@($s.execution.common.tools)-join',')-ceq'Read,StructuredOutput'-and$s.execution.common.result-ceq'route-review-result.v1') 'tools/result';A ($s.execution.fable.model-ceq'claude-fable-5'-and$s.execution.opus.model-ceq'claude-opus-5'-and$s.execution.sonnet.model-ceq'claude-sonnet-5') 'models';A ($s.authority-ceq'ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX') 'matrix authority'
foreach($c in $s.cases){A ($c.Count-eq3-and(E $c[1])-ceq$c[2]) "executed case $($c[0])"}
$bundlePath=Join-Path $repo 'receipts\opus-model-failback-r27-evidence-bundle-20260826.json';$bundleRaw=[IO.File]::ReadAllText($bundlePath);$b=$bundleRaw|ConvertFrom-Json -Depth 20 -DateKind String
K $b 'schema,closed_keys,created_at_utc,prior_r26,current_fable,current_opus,current_control_chain,contract,authority' 'bundle keys';A ($b.schema-ceq'fleet-opus-model-failback-evidence-bundle.v22'-and$b.closed_keys) 'bundle identity'
K $b.prior_r26 'commit,tree,core_sha256,bundle_sha256,test_sha256' 'r26 keys';A ($b.prior_r26.commit-ceq'854BDBE3AC807675FE6EF1405B5CD1414FCB4B39'-and$b.prior_r26.tree-ceq'9E2EEA3E09637998B5A2997BD5A1407249019326'-and$b.prior_r26.core_sha256-ceq'B0761F8ECA386EC7BDA12529B48FF09D2937FB52ACE1AD11BDE69884A095D9A6') 'r26 ancestry'
$f=$b.current_fable;K $f 'disposition,route_id,packet_sha256,session_id,model,effort,role,turns,input_tokens,output_tokens,verdict,consumption_receipt_sha256,artifact_sha256,review_result_sha256,lease_released,actionable_findings' 'fable keys';A ($f.disposition-ceq'ACCEPT'-and$f.route_id-ceq'failback-r26-fable-core-r1'-and$f.packet_sha256-ceq'9D07E92C3DC113D30A3E0FF80DCD1404C3AFAB302201E341995A35BC65848F92'-and$f.session_id-ceq'31b064ad-e4da-44f3-b4cc-ae44d42d800b') 'exact r26 fable route packet session';A ($f.model-ceq'claude-fable-5'-and$f.effort-ceq'max'-and$f.role-ceq'coordinator'-and$f.turns-eq8-and$f.input_tokens-eq8-and$f.output_tokens-eq25272-and$f.verdict-ceq'ACCEPT'-and$f.lease_released-and$f.actionable_findings-eq0) 'exact r26 fable acceptance';A ((S $f.consumption_receipt_sha256)-and(S $f.artifact_sha256)-and(S $f.review_result_sha256)) 'fable acceptance hashes'
$o=$b.current_opus;K $o 'disposition,route_id,packet_sha256,session_id,model,effort,role,turns,input_tokens,output_tokens,verdict,consumption_receipt_sha256,artifact_sha256,review_result_sha256,lease_released,actionable_findings' 'opus keys';A ($o.disposition-ceq'ACCEPT'-and$o.route_id-ceq'failback-r26-opus-core-r1'-and$o.packet_sha256-ceq'528F436AFAF7C9ED9F8686CDDBCE0734CD525BB58F7B224195C8A45CA5FB6330'-and$o.session_id-ceq'4bbca206-ca2d-494e-b7ef-78692654086e') 'exact r26 opus route packet session';A ($o.model-ceq'claude-opus-5'-and$o.effort-ceq'max'-and$o.role-ceq'executor'-and$o.turns-eq7-and$o.input_tokens-eq6-and$o.output_tokens-eq24710-and$o.verdict-ceq'ACCEPT'-and$o.lease_released-and$o.actionable_findings-eq0) 'exact r26 opus acceptance';A ((S $o.consumption_receipt_sha256)-and(S $o.artifact_sha256)-and(S $o.review_result_sha256)) 'opus acceptance hashes'
K $b.current_control_chain 'gate_rebind_schema,gate_rebind_transaction_sha256,policy_sha256,observer_sha256,admission_sha256,warden_sha256,route_planner_sha256,reserve_pct,hard_ceiling,provider_launches,model_inference' 'control chain keys';A ($b.current_control_chain.gate_rebind_schema-ceq'fleet-provider-gate-policy-rebind.v2'-and$b.current_control_chain.gate_rebind_transaction_sha256-ceq'ED3782F5691D0BB5A65B2BA69FA3580C66BA78BF46C8035FEF9737C7ED41FE35'-and$b.current_control_chain.policy_sha256-ceq'5FD2B4B7E9DF16ADDA646C6AB62782EEAD2701F464FDC705A3F23808CB7B4C06'-and$b.current_control_chain.observer_sha256-ceq'5BFA600269826DBA3155FD29AB0E391E8581A2C82CC7180338D59302C83A9B7E'-and$b.current_control_chain.admission_sha256-ceq'AB85C9018A52FFF17D363DCD0C23E38F60CB7806CBE5D8C10CFAD0CDBE1CFBD7'-and$b.current_control_chain.reserve_pct-eq0-and$b.current_control_chain.hard_ceiling-eq100-and$b.current_control_chain.provider_launches-eq0-and-not$b.current_control_chain.model_inference) 'current control chain'
K $b.contract 'cases,repeats,max_age,ceiling,subject_max,aggregate_max,subject_count,hidden_reads,capsule_schema,capacity_materialization' 'contract keys';A ($b.contract.cases-eq35-and$b.contract.repeats-eq3-and$b.contract.max_age-eq300-and$b.contract.ceiling-eq100-and$b.contract.subject_max-eq24576-and$b.contract.aggregate_max-eq32768-and$b.contract.subject_count-eq4-and$b.contract.hidden_reads-eq0-and$b.contract.capsule_schema-ceq'fleet-opus-model-failback-verification-capsule.v15'-and$b.contract.capacity_materialization-ceq'POST_ROUTE_PRECLAIM_DYNAMIC') 'contract'
$candidatePath=Join-Path $repo 'ruling-candidates\opus-model-failback-r4.md';$candidate=[IO.File]::ReadAllText($candidatePath);A ($candidate.StartsWith('# Ruling candidate: exhausted-model failback to Opus R27')) 'candidate title';foreach($term in @('all three on-lane core rows','terminal_reason=api_error','assistant_error=rate_limit','exact terminal carrier bytes','independent core mutations','independent execution mutations','34,814 output tokens','Sonnet must ACCEPT','must not freeze a live capacity sample','post-route/preclaim capacity-materialization boundary','current reservation-aware policy')){A ($candidate.Contains($term)) "candidate $term"}
$rels=@('ruling-candidates/opus-model-failback-r4.md','tests/test-opus-model-failback-r12-controls.ps1','receipts/opus-model-failback-r27-evidence-bundle-20260826.json');$rows=[Collections.Generic.List[object]]::new();foreach($r in $rels){$p=Join-Path $repo ($r-replace'/',[IO.Path]::DirectorySeparatorChar);$i=Get-Item -LiteralPath $p;$rows.Add([ordered]@{path=$r;bytes=[int64]$i.Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash})};$core=Q ($rows|ConvertTo-Json -Compress -Depth 5);A ($core-ceq$ExpectedCoreDigest.ToUpperInvariant()) 'external core digest';A (@($rows|Where-Object{$_.bytes-gt24576}).Count-eq0) 'subject fit';$mut=@($rows|ForEach-Object{[ordered]@{path=$_.path;bytes=$_.bytes;sha256=$_.sha256}});$mut[0].sha256='0'*64;A ((Q ($mut|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row mutation';A ((Q (@($rows[1],$rows[0],$rows[2])|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row order'
$capFile=[IO.Path]::GetFullPath($VerificationCapsulePath);$capRaw=[IO.File]::ReadAllText($capFile);$cap=$capRaw|ConvertFrom-Json -Depth 20 -DateKind String;K $cap 'schema,generation,lane,packet,ancestry,core,git,local,prior,current_fable,current_opus,capacity_control,authority' 'capsule keys';A ($cap.schema-ceq'fleet-opus-model-failback-verification-capsule.v15'-and$cap.generation-ceq'opus-model-failback-r27'-and$cap.lane-in@('fable','opus','sonnet')) 'capsule identity'
K $cap.packet 'route_id,issued_at_utc,expires_at_utc' 'capsule packet keys';$packetFile=[IO.Path]::GetFullPath($IssuingPacketPath);$packetRaw=[IO.File]::ReadAllText($packetFile);$packet=$packetRaw|ConvertFrom-Json -Depth 20 -DateKind String;K $packet 'schema,route_id,lane,role,authority,objective,issued_at_utc,expires_at_utc,actionable_work,no_subagents,no_lane_reopen,subjects,result_contract' 'packet keys';$bad=@($packet.subjects|Where-Object{(@($_.PSObject.Properties.Name)-join',')-cne'path,bytes,sha256'-or$_.path-isnot[string]-or$_.sha256-isnot[string]-or[Type]::GetTypeCode($_.bytes.GetType())-notin@([TypeCode]::SByte,[TypeCode]::Byte,[TypeCode]::Int16,[TypeCode]::UInt16,[TypeCode]::Int32,[TypeCode]::UInt32,[TypeCode]::Int64,[TypeCode]::UInt64)});A ($packet.schema-is[string]-and$packet.authority-is[string]-and$packet.result_contract-is[string]-and$packet.actionable_work-is[bool]-and$packet.no_subagents-is[bool]-and$packet.no_lane_reopen-is[bool]-and$packet.subjects-is[array]-and$bad.Count-eq0) 'native packet types';A ($packet.schema-ceq'dng-headless-route.v1'-and$packet.authority-ceq'read-only-review'-and$packet.result_contract-ceq'route-review-result.v1'-and$packet.route_id-ceq$cap.packet.route_id-and$packet.issued_at_utc-ceq$cap.packet.issued_at_utc-and$packet.expires_at_utc-ceq$cap.packet.expires_at_utc-and$packet.lane-ceq$cap.lane-and$packet.actionable_work-and$packet.no_subagents-and$packet.no_lane_reopen) 'packet binding';$capRow=@($packet.subjects|Where-Object{[IO.Path]::GetFullPath($_.path)-ceq$capFile});A ($capRow.Count-eq1-and$capRow[0].bytes-eq(Get-Item $capFile).Length-and$capRow[0].sha256-ceq(Q $capRaw)) 'capsule row';for($i=0;$i-lt$rows.Count;$i++){$pr=$packet.subjects[$i];$ep=[IO.Path]::GetFullPath((Join-Path $repo ($rows[$i].path-replace'/',[IO.Path]::DirectorySeparatorChar)));A ([IO.Path]::GetFullPath([string]$pr.path)-ceq$ep-and[int64]$pr.bytes-eq[int64]$rows[$i].bytes-and[string]$pr.sha256-ceq[string]$rows[$i].sha256) "exact on-lane core row $i"}
K $cap.ancestry 'packet_sha256,consumption_receipt_sha256,review_result_sha256,route_id,session_id,model,core_sha256' 'ancestry keys';A ((S $cap.ancestry.packet_sha256)-and(S $cap.ancestry.consumption_receipt_sha256)-and(S $cap.ancestry.review_result_sha256)-and$cap.ancestry.session_id-cmatch'^[0-9a-f-]{36}$'-and(S $cap.ancestry.core_sha256)) 'ancestry shape';A ($cap.core.format-ceq'SHA256_CANONICAL_CLOSED_KEY_ORDERED_ROWS_V1'-and$cap.core.sha256-ceq$core-and$cap.core.subject_count-eq3-and$cap.core.bytes-eq(($rows|ForEach-Object{$_.bytes}|Measure-Object -Sum).Sum)) 'core';A ($cap.git.commit-cmatch'^[A-F0-9]{40}$'-and$cap.git.tree-cmatch'^[A-F0-9]{40}$'-and$cap.git.branch-ceq'codex/opus-model-failback-r27-ratification-candidate'-and$cap.git.clean) 'git'
K $cap.prior 'bundle_sha256,bundle_schema,fable_verdict,opus_verdict,adoption_credit' 'prior keys';A ($cap.prior.bundle_sha256-ceq(Q $bundleRaw)-and$cap.prior.bundle_schema-ceq$b.schema-and$cap.prior.fable_verdict-ceq'ACCEPT'-and$cap.prior.opus_verdict-ceq'ACCEPT'-and$cap.prior.adoption_credit-ceq'ZERO') 'prior'
$cf=$cap.current_fable;K $cf 'disposition,route_id,packet_sha256,session_id,model,effort,role,turns,input_tokens,output_tokens,verdict,consumption_receipt_sha256,artifact_sha256,review_result_sha256,lease_released,actionable_findings' 'current fable keys';A ($cf.disposition-ceq'ACCEPT'-and$cf.model-ceq'claude-fable-5'-and$cf.effort-ceq'max'-and$cf.role-ceq'coordinator'-and$cf.verdict-ceq'ACCEPT'-and$cf.lease_released-and$cf.actionable_findings-eq0-and$cf.input_tokens-gt0-and$cf.output_tokens-gt0) 'current fable acceptance';A ((S $cf.packet_sha256)-and(S $cf.consumption_receipt_sha256)-and(S $cf.artifact_sha256)-and(S $cf.review_result_sha256)) 'current fable hashes';if($cap.lane-ceq'fable'){A (($cf|ConvertTo-Json -Compress)-ceq($f|ConvertTo-Json -Compress)) 'r26 fable extract';A ($cap.ancestry.core_sha256-ceq$b.prior_r26.core_sha256) 'r26 core ancestry'}else{A ($cf.route_id-cmatch'^failback-r27-fable-core') 'r27 fable route';A ($cap.ancestry.core_sha256-ceq$core) 'r27 core ancestry'}
$co=$cap.current_opus;K $co 'disposition,route_id,packet_sha256,session_id,model,effort,role,turns,input_tokens,output_tokens,verdict,consumption_receipt_sha256,artifact_sha256,review_result_sha256,lease_released,actionable_findings' 'current opus keys';A ($co.disposition-ceq'ACCEPT'-and$co.model-ceq'claude-opus-5'-and$co.effort-ceq'max'-and$co.role-ceq'executor'-and$co.verdict-ceq'ACCEPT'-and$co.lease_released-and$co.actionable_findings-eq0-and$co.input_tokens-gt0-and$co.output_tokens-gt0) 'current opus acceptance';A ((S $co.packet_sha256)-and(S $co.consumption_receipt_sha256)-and(S $co.artifact_sha256)-and(S $co.review_result_sha256)) 'current opus hashes';if($cap.lane-ceq'sonnet'){A ($co.route_id-cmatch'^failback-r27-opus-core') 'r27 opus route';A ($cap.ancestry.core_sha256-ceq$core) 'sonnet core ancestry'}else{A (($co|ConvertTo-Json -Compress)-ceq($o|ConvertTo-Json -Compress)) 'r26 opus extract';A ($cap.ancestry.core_sha256-in@($b.prior_r26.core_sha256,$core)) 'pre-sonnet ancestry'}
K $cap.capacity_control 'mode,route_stage,observer_path,observer_sha256,admission_path,admission_sha256,policy_path,policy_sha256,warden_path,warden_sha256,route_planner_path,route_planner_sha256,max_age_seconds,ceiling,reserve_pct,estimate_5h,estimate_7d,assertion' 'capacity control keys';A ($cap.capacity_control.mode-ceq'POST_ROUTE_PRECLAIM_DYNAMIC_SIGNED_SAMPLE'-and$cap.capacity_control.observer_sha256-ceq'5BFA600269826DBA3155FD29AB0E391E8581A2C82CC7180338D59302C83A9B7E'-and$cap.capacity_control.admission_sha256-ceq'AB85C9018A52FFF17D363DCD0C23E38F60CB7806CBE5D8C10CFAD0CDBE1CFBD7'-and$cap.capacity_control.policy_sha256-ceq'5FD2B4B7E9DF16ADDA646C6AB62782EEAD2701F464FDC705A3F23808CB7B4C06'-and$cap.capacity_control.warden_sha256-ceq'8C09B1A8D6D2FA439FB113BE1C772908A9B0FB4E1DB35FE6269B5A1C30D0D27C'-and$cap.capacity_control.route_planner_sha256-ceq'113D65DC626520C10A6F4BAFEBA876F602BBA54C7CE3C7E70E848D4F6B746C4F') 'capacity control identities';A ($cap.capacity_control.route_stage-ceq'ROUTE_VALIDATED_THEN_OBSERVER_THEN_PRECLAIM_THEN_PERMIT_THEN_ADMISSION'-and$cap.capacity_control.observer_path-ceq'DngAutoProcessor/scripts/observe-fleet-provider-capacity.ps1'-and$cap.capacity_control.admission_path-ceq'DngAutoProcessor/scripts/invoke-fleet-provider-admission.ps1'-and$cap.capacity_control.policy_path-ceq'DngAutoProcessor/scripts/fleet-provider-admission.policy.json'-and$cap.capacity_control.warden_path-ceq'coordination/tools/warden-wake.ps1'-and$cap.capacity_control.route_planner_path-ceq'coordination/tools/route-first-headless-r2.1-lib.ps1') 'capacity control flow';A ($cap.capacity_control.max_age_seconds-eq$s.capacity_max_age_seconds-and$cap.capacity_control.ceiling-eq$s.hard_ceiling-and$cap.capacity_control.reserve_pct-eq0-and$cap.capacity_control.estimate_5h-eq5-and$cap.capacity_control.estimate_7d-eq5-and$cap.capacity_control.assertion) 'capacity control invariants';A ($null-eq$cap.capacity_control.PSObject.Properties['observed_at_utc']-and$null-eq$cap.capacity_control.PSObject.Properties['proof']-and$null-eq$cap.capacity_control.PSObject.Properties['u5']-and$null-eq$cap.capacity_control.PSObject.Properties['u7']) 'no frozen capacity sample'
K $cap.local 'path,sha256,command,repeats,assertions,cases,pass_sha256' 'local keys';$selfHash=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;$expected=@{fable=111;opus=111;sonnet=111};A ($cap.local.path-ceq'tests/test-opus-model-failback-r12-controls.ps1'-and$cap.local.sha256-ceq$selfHash-and$cap.local.command-ceq'pwsh r12'-and$cap.local.repeats-eq3-and$cap.local.assertions-eq$expected[$cap.lane]-and$cap.local.cases-eq35-and(S $cap.local.pass_sha256)) "exact local assertions expected=$($expected[$cap.lane]) provided=$($cap.local.assertions)"
A ($cap.authority-ceq'READ_ONLY_EVIDENCE_ZERO_PROVIDER_ZERO_ACCEPTANCE_ZERO_ADOPTION') 'authority';$coreBytes=($rows|ForEach-Object{$_.bytes}|Measure-Object -Sum).Sum;A ($rows.Count+1-le4-and$coreBytes+(Get-Item $capFile).Length-le32768) 'r2.1 fit'
"PASS SUITE - $script:n assertions; 35 EXECUTED CASES; VERIFIED_CAPSULE_V15; ACCEPTED_R26_CHAIN_BOUND; CURRENT_CONTROL_CHAIN_BOUND; CLOSED_CONTRACT; POST_ROUTE_DYNAMIC_CAPACITY; ZERO_PROVIDER; ZERO_WRITES; CORE=$core"
