[CmdletBinding()]param([Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$ExpectedCoreDigest,[Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$ContinuationAncestryPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$script:n=0
function A([bool]$ok,[string]$m){if(-not$ok){throw "ASSERTION FAILED: $m"};$script:n++}
function Get-TextSha([string]$text){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.UTF8Encoding]::new($false).GetBytes($text)))}
$j=@'
{"schema":"fleet-exhausted-model-failback-controls.v7","candidate":"opus-model-failback-r8","authority":"ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX","capacity_max_age_seconds":300,"hard_ceiling":100,"core":{"algorithm":"SHA256_CANONICAL_CLOSED_KEY_ORDERED_ROWS_V1","keys":["path","bytes","sha256"],"order_binding":true,"ancestry_excluded":true,"expected_digest_external":true},"execution":{"common":{"effort":"max","turns":12,"wall_seconds":900,"tools":["Read","StructuredOutput"],"result":"route-review-result.v1"},"fable":{"model":"claude-fable-5","role":"coordinator"},"opus":{"model":"claude-opus-5","role":"executor"}},"assertions":["INIT_MODEL_EXACT","ROUTE_AND_SESSION_EXACT","TERMINAL_REASON_API_ERROR","HTTP_STATUS_429","EXACTLY_ONE_TURN","EXACT_MODEL_SCOPED_RESULT_TEXT","ASSISTANT_ERROR_RATE_LIMIT","ZERO_REVIEW_INPUT_TOKENS","ZERO_REVIEW_OUTPUT_TOKENS","NO_REVIEW_VERDICT_OR_ACCEPTANCE","RATE_LIMIT_EVENTS_COMPLETE_AND_ADJUDICATED","SAME_DOMAIN_CAPACITY_FRESH","CAPACITY_PLUS_ACTIVE_RESERVATIONS_PLUS_CONSERVATIVE_OPUS_ESTIMATE_LTE_100_EVERY_WINDOW"],"classifier":{"bind_all":true,"base_rejected":"HOLD_ACCOUNT_OR_WINDOW_EXHAUSTION","overage_allowed_base":"CONTINUE","overage_omitted_base_exact_signed":"CONTINUE","overage_uncorroborated":"HOLD_CLASSIFIER_AMBIGUOUS","unknown":"HOLD_CLASSIFIER_AMBIGUOUS"},"continuation_ancestry":{"single_attachment":true,"required_keys":["fable_exhaustion_receipt_sha256","hold_disposition_sha256","terminal_lease_sha256","capacity_observed_at_utc","attachment_created_at_utc","capacity_age_seconds","fable_account_domain","capacity_account_domain","utilization_by_window","active_reservations_by_window","conservative_opus_estimate_by_window","sum_by_window","hard_ceiling","no_overlap"]},"cases":[
{"id":"positive_exact_fable_exhaustion","mutation":"none","expected":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","writes":0,"provider_launches":0},
{"id":"wrong_or_alias_fable_model","mutation":"model","expected":"HOLD_MODEL_IDENTITY","writes":0,"provider_launches":0},
{"id":"generic_429_without_exact_fable_text","mutation":"text","expected":"HOLD_EXHAUSTION_AMBIGUOUS","writes":0,"provider_launches":0},
{"id":"assistant_error_missing_or_different","mutation":"error","expected":"HOLD_TERMINAL_EVIDENCE","writes":0,"provider_launches":0},
{"id":"nonterminal_or_multiturn_result","mutation":"terminal","expected":"HOLD_TERMINAL_IDENTITY","writes":0,"provider_launches":0},
{"id":"verdict_or_acceptance_present","mutation":"credit","expected":"HOLD_CREDIT_CONFLICT","writes":0,"provider_launches":0},
{"id":"nonzero_fable_review_tokens","mutation":"tokens","expected":"HOLD_NOT_ZERO_CREDIT_EXHAUSTION","writes":0,"provider_launches":0},
{"id":"rate_limit_event_omitted","mutation":"event","expected":"HOLD_CLASSIFIER_INCOMPLETE","writes":0,"provider_launches":0},
{"id":"base_window_rejected","mutation":"base","expected":"HOLD_ACCOUNT_OR_WINDOW_EXHAUSTION","writes":0,"provider_launches":0},
{"id":"overage_only_rejected_with_allowed_base_below_100","mutation":"allowed","expected":"CONTINUE_TO_OTHER_GATES","writes":0,"provider_launches":0},
{"id":"overage_only_rejected_without_base_event_with_exact_model_evidence_and_signed_base_below_100","mutation":"omitted","expected":"CONTINUE_TO_OTHER_GATES","writes":0,"provider_launches":0},
{"id":"overage_only_rejected_without_base_event_or_fresh_signed_corroboration","mutation":"unsigned","expected":"HOLD_CLASSIFIER_AMBIGUOUS","writes":0,"provider_launches":0},
{"id":"contradictory_or_unenumerated_rate_limit_event","mutation":"unknown","expected":"HOLD_CLASSIFIER_AMBIGUOUS","writes":0,"provider_launches":0},
{"id":"stale_capacity","mutation":"stale","expected":"HOLD_CAPACITY_EVIDENCE","writes":0,"provider_launches":0},
{"id":"cross_domain_capacity","mutation":"cross_domain","expected":"HOLD_CAPACITY_EVIDENCE","writes":0,"provider_launches":0},
{"id":"same_domain_successor_capacity","mutation":"same_domain","expected":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","writes":0,"provider_launches":0},
{"id":"hard_ceiling_sum_exactly_100","mutation":"eq100","expected":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","writes":0,"provider_launches":0},
{"id":"hard_ceiling_sum_above_100","mutation":"gt100","expected":"HOLD_HARD_CEILING","writes":0,"provider_launches":0},
{"id":"core_subject_reordered","mutation":"order","expected":"HOLD_CORE_SUBJECT_DIGEST","writes":0,"provider_launches":0},
{"id":"core_subject_replaced","mutation":"replace","expected":"HOLD_CORE_SUBJECT_DIGEST","writes":0,"provider_launches":0},
{"id":"core_digest_row_mutated","mutation":"core_mutated","expected":"HOLD_CORE_SUBJECT_DIGEST","writes":0,"provider_launches":0},
{"id":"execution_contract_effort_drift","mutation":"effort","expected":"HOLD_EXECUTION_CONTRACT","writes":0,"provider_launches":0},
{"id":"execution_contract_turn_or_wall_drift","mutation":"bounds","expected":"HOLD_EXECUTION_CONTRACT","writes":0,"provider_launches":0},
{"id":"execution_contract_model_role_or_tools_drift","mutation":"identity","expected":"HOLD_EXECUTION_CONTRACT","writes":0,"provider_launches":0},
{"id":"assertion_map_count_mismatch","mutation":"map","expected":"HOLD_ASSERTION_MAP","writes":0,"provider_launches":0},
{"id":"open_gate","mutation":"gate","expected":"HOLD_OPEN_GATE","writes":0,"provider_launches":0},
{"id":"live_provider_lease_or_concurrent_transaction","mutation":"overlap","expected":"HOLD_OVERLAP","writes":0,"provider_launches":0},
{"id":"unconsumed_canary","mutation":"unconsumed","expected":"HOLD_UNCONSUMED_CANARY","writes":0,"provider_launches":0},
{"id":"consumed_canary_not_authority","mutation":"consumed","expected":"CONTINUE_TO_LATER_GATES_WITH_ZERO_ADMISSION_AUTHORITY","writes":0,"provider_launches":0},
{"id":"account_domain_rotation_failure","mutation":"rotation","expected":"ROLLED_BACK_AND_HOLD","writes":0,"provider_launches":0},
{"id":"malformed_structured_output","mutation":"malformed","expected":"HOLD_MALFORMED_OUTPUT","writes":0,"provider_launches":0},
{"id":"continuation_ancestry_missing_or_stale","mutation":"ancestry","expected":"HOLD_CONTINUATION_ANCESTRY","writes":0,"provider_launches":0},
{"id":"terminal_retirement_overclaim","mutation":"lease","expected":"REVISE_EVIDENCE_CLAIM","writes":0,"provider_launches":0}],"credit":"NEXT_GATE_ONLY_ZERO_AUTHORITY"}
'@
function E([string]$mutation){
 $x=[ordered]@{model=$true;text=$true;error=$true;terminal=$true;credit=$false;tokens=0;event='allowed';fresh=$true;fableDomain='opaque-a';capacityDomain='opaque-a';u5=14;u7=88;r5=0;r7=0;e5=5;e7=5;core=$true;execution=$true;map=$true;gate='closed';overlap=$false;canary='none';rotation=$true;output=$true;ancestry=$true;lease='truthful'}
 switch($mutation){model{$x.model=$false}text{$x.text=$false}error{$x.error=$false}terminal{$x.terminal=$false}credit{$x.credit=$true}tokens{$x.tokens=1}event{$x.event='missing'}base{$x.event='base'}allowed{$x.event='allowed'}omitted{$x.event='omitted'}unsigned{$x.event='uncorroborated'}unknown{$x.event='unknown'}stale{$x.fresh=$false}cross_domain{$x.capacityDomain='opaque-b'}same_domain{$x.fableDomain='opaque-b';$x.capacityDomain='opaque-b'}eq100{$x.u5=90;$x.r5=5;$x.e5=5}gt100{$x.u5=91;$x.r5=5;$x.e5=5}order{$x.core=$false}replace{$x.core=$false}core_mutated{$x.core=$false}effort{$x.execution=$false}bounds{$x.execution=$false}identity{$x.execution=$false}map{$x.map=$false}gate{$x.gate='open'}overlap{$x.overlap=$true}unconsumed{$x.canary='unconsumed'}consumed{$x.canary='consumed'}rotation{$x.rotation=$false}malformed{$x.output=$false}ancestry{$x.ancestry=$false}lease{$x.lease='overclaim'}none{}default{throw "unknown mutation $mutation"}}
 if(-not$x.model){return 'HOLD_MODEL_IDENTITY'};if(-not$x.text){return 'HOLD_EXHAUSTION_AMBIGUOUS'};if(-not$x.error){return 'HOLD_TERMINAL_EVIDENCE'};if(-not$x.terminal){return 'HOLD_TERMINAL_IDENTITY'};if($x.credit){return 'HOLD_CREDIT_CONFLICT'};if($x.tokens-ne0){return 'HOLD_NOT_ZERO_CREDIT_EXHAUSTION'}
 if($x.event-ceq'missing'){return 'HOLD_CLASSIFIER_INCOMPLETE'};if($x.event-ceq'base'){return 'HOLD_ACCOUNT_OR_WINDOW_EXHAUSTION'};if($x.event-in@('uncorroborated','unknown')){return 'HOLD_CLASSIFIER_AMBIGUOUS'};if(-not$x.fresh-or$x.fableDomain-cne$x.capacityDomain){return 'HOLD_CAPACITY_EVIDENCE'}
 if(($x.u5+$x.r5+$x.e5)-gt100-or($x.u7+$x.r7+$x.e7)-gt100){return 'HOLD_HARD_CEILING'};if(-not$x.core){return 'HOLD_CORE_SUBJECT_DIGEST'};if(-not$x.execution){return 'HOLD_EXECUTION_CONTRACT'};if(-not$x.map){return 'HOLD_ASSERTION_MAP'};if($x.gate-cne'closed'){return 'HOLD_OPEN_GATE'};if($x.overlap){return 'HOLD_OVERLAP'};if($x.canary-ceq'unconsumed'){return 'HOLD_UNCONSUMED_CANARY'};if(-not$x.rotation){return 'ROLLED_BACK_AND_HOLD'};if(-not$x.output){return 'HOLD_MALFORMED_OUTPUT'};if(-not$x.ancestry){return 'HOLD_CONTINUATION_ANCESTRY'};if($x.lease-cne'truthful'){return 'REVISE_EVIDENCE_CLAIM'}
 if($x.canary-ceq'consumed'){return 'CONTINUE_TO_LATER_GATES_WITH_ZERO_ADMISSION_AUTHORITY'};if($x.event-in@('allowed','omitted')-and$mutation-in@('allowed','omitted')){return 'CONTINUE_TO_OTHER_GATES'};return 'ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION'
}
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$candidate=[IO.File]::ReadAllText((Join-Path $repo 'ruling-candidates\opus-model-failback-r1.md'));$flat=$candidate-replace'\s+',' ';$s=$j|ConvertFrom-Json -Depth 20
$bundlePath=Join-Path $repo 'receipts\opus-model-failback-r8-evidence-bundle-20260825.json';$b=[IO.File]::ReadAllText($bundlePath)|ConvertFrom-Json -Depth 20
A ($s.schema-ceq'fleet-exhausted-model-failback-controls.v7') 'schema';A ($s.candidate-ceq'opus-model-failback-r8') 'candidate';A ($s.authority-ceq'ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX') 'authority';A ($s.capacity_max_age_seconds-eq300) 'age';A ($s.hard_ceiling-eq100) 'ceiling';A ($s.assertions.Count-eq13) 'assertion count';A ((@($s.assertions|Sort-Object -Unique)).Count-eq13) 'assertion unique';A ('CAPACITY_PLUS_ACTIVE_RESERVATIONS_PLUS_CONSERVATIVE_OPUS_ESTIMATE_LTE_100_EVERY_WINDOW'-cin$s.assertions) 'sum assertion';A $s.classifier.bind_all 'bind all'
A ($s.execution.common.effort-ceq'max') 'effort';A ($s.execution.common.turns-eq12) 'turns';A ($s.execution.common.wall_seconds-eq900) 'wall';A ((@($s.execution.common.tools)-join',')-ceq'Read,StructuredOutput') 'tools';A ($s.execution.fable.model-ceq'claude-fable-5'-and$s.execution.fable.role-ceq'coordinator') 'fable';A ($s.execution.opus.model-ceq'claude-opus-5'-and$s.execution.opus.role-ceq'executor') 'opus';A ($s.cases.Count-eq33) 'case count'
$ids=@($s.cases.id);A ((@($ids|Sort-Object -Unique)).Count-eq33) 'case unique';foreach($id in @('stale_capacity','cross_domain_capacity','same_domain_successor_capacity','malformed_structured_output','continuation_ancestry_missing_or_stale','core_digest_row_mutated','core_subject_reordered')){A ($id-cin$ids) "required $id"}
A ($s.continuation_ancestry.single_attachment) 'single ancestry';A ($s.continuation_ancestry.required_keys.Count-eq14) 'ancestry keys';A ((@($s.continuation_ancestry.required_keys|Sort-Object -Unique)).Count-eq14) 'ancestry unique'
foreach($c in $s.cases){A ((@($c.PSObject.Properties.Name|Sort-Object)-join',')-ceq'expected,id,mutation,provider_launches,writes') "keys $($c.id)";A ($c.writes-eq0) "writes $($c.id)";A ($c.provider_launches-eq0) "launches $($c.id)";A ((E $c.mutation)-ceq$c.expected) "executed $($c.id)"}
A ($b.schema-ceq'fleet-opus-model-failback-evidence-bundle.v3'-and$b.closed_keys) 'bundle';A ($b.source_receipts.Count-eq7) 'sources';A ((@($b.review_history.actionable_findings)-join',')-ceq'9,3,6,5,6') 'review history';A ($b.r5_disposition.provider_launches-eq0-and$b.r5_disposition.review_credit-ceq'ZERO') 'r5 no review';A ($b.r7_actionable_findings.Count-eq6) 'r7 findings';A ($b.r8_contract.terminal_assertion_count-eq13-and$b.r8_contract.executed_matrix_cases-eq33) 'r8 contract';A ($b.r8_contract.continuation_ancestry_subject.required_keys.Count-eq14-and$b.r8_contract.shipped_ancestry_validation) 'bundle ancestry'
$sourceMap=@{production_path_revise_9='dng-opus-model-failback-20260824.json';r1_opus_revise_3='opus-model-failback-r1-independent-opus-revise-20260825.json';r2_opus_revise_6='opus-model-failback-r2-independent-opus-revise-20260825.json';r3_allowed_base_adjudication='fable-model-exhaustion-adjudication-r3-20260825.json';r4_omitted_base_variant='fable-classifier-variant-r4-20260825.json';r6_opus_revise_5='opus-model-failback-r6-independent-opus-revise-20260825.json';r7_opus_revise_6='opus-model-failback-r7-independent-opus-revise-20260825.json'}
foreach($src in $b.source_receipts){A ($src.sha256-cmatch'^[A-F0-9]{64}$') "source hash $($src.id)";if($sourceMap.ContainsKey($src.id)){A ((Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $repo "receipts\$($sourceMap[$src.id])")).Hash-ceq$src.sha256) "source bytes $($src.id)"}}
A ($candidate.StartsWith('# Ruling candidate: exhausted-model failback to Opus R8')) 'title';A ($candidate.Contains('active reservations')) 'reservations';A ($candidate.Contains('single closed-key subject binds')) 'ancestry doctrine';A ($flat.Contains('R1 returned 3, R2 returned 6, R6 returned 5, and R7 returned 6')) 'history doctrine';A ($candidate.Contains('R5 was carrier-rejected')) 'r5 doctrine';A ($flat.Contains('Every mutation must be executed')) 'mutation doctrine'
$rels=@('ruling-candidates/opus-model-failback-r1.md','tests/test-opus-model-failback-r3-controls.ps1','receipts/opus-model-failback-r8-evidence-bundle-20260825.json');$rows=[Collections.Generic.List[object]]::new();foreach($r in $rels){$p=Join-Path $repo ($r-replace'/',[IO.Path]::DirectorySeparatorChar);$i=Get-Item -LiteralPath $p;$rows.Add([ordered]@{path=$r;bytes=[int64]$i.Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash})};$raw=$rows|ConvertTo-Json -Compress -Depth 5;$core=Get-TextSha $raw;A ($core-ceq$ExpectedCoreDigest.ToUpperInvariant()) 'external core digest'
$mut=[Collections.Generic.List[object]]::new();foreach($r in $rows){$mut.Add([ordered]@{path=$r.path;bytes=$r.bytes;sha256=$r.sha256})};$mut[0].sha256='0'*64;$mutRaw=$mut|ConvertTo-Json -Compress -Depth 5;A ((Get-TextSha $mutRaw)-cne$core) 'changed row digest rejected'
$perm=@($rows[1],$rows[0],$rows[2]);$permRaw=$perm|ConvertTo-Json -Compress -Depth 5;A ((Get-TextSha $permRaw)-cne$core) 'permuted row digest rejected'
$ancFile=[IO.Path]::GetFullPath($ContinuationAncestryPath);$ancRaw=[IO.File]::ReadAllText($ancFile);$anc=$ancRaw|ConvertFrom-Json -Depth 10;$ancBytes=(Get-Item -LiteralPath $ancFile).Length;$coreBytes=0;foreach($r in $rows){$coreBytes+=[int64]$r.bytes}
A ((@($anc.PSObject.Properties.Name)-join',')-ceq(@($s.continuation_ancestry.required_keys)-join',')) 'shipped ancestry closed keys';foreach($k in @('fable_exhaustion_receipt_sha256','hold_disposition_sha256','terminal_lease_sha256')){A ($anc.$k-cmatch'^[A-F0-9]{64}$') "ancestry hash $k"};A ($anc.fable_account_domain-ceq$anc.capacity_account_domain-and$anc.fable_account_domain-cmatch'^anthropic-org/hmac-sha256:[a-f0-9]{64}$') 'shipped ancestry same domain'
$observed=[datetime]$anc.capacity_observed_at_utc;$created=[datetime]$anc.attachment_created_at_utc;$derivedAge=($created-$observed).TotalSeconds;A ($derivedAge-ge0-and$derivedAge-le$s.capacity_max_age_seconds) 'reproducible ancestry freshness';A ([Math]::Abs($derivedAge-[double]$anc.capacity_age_seconds)-lt0.001) 'published ancestry age exact';A ($anc.no_overlap-eq$true) 'shipped ancestry no overlap';A ($anc.sum_by_window.five_hour-eq($anc.utilization_by_window.five_hour+$anc.active_reservations_by_window.five_hour+$anc.conservative_opus_estimate_by_window.five_hour)-and$anc.sum_by_window.seven_day-eq($anc.utilization_by_window.seven_day+$anc.active_reservations_by_window.seven_day+$anc.conservative_opus_estimate_by_window.seven_day)) 'ancestry sums';A ($anc.sum_by_window.five_hour-le$anc.hard_ceiling-and$anc.sum_by_window.seven_day-le$anc.hard_ceiling) 'ancestry ceiling';A ($coreBytes+$ancBytes-le32768-and$ancBytes-le24kb-and$rows.Count+1-le4) 'r2.1 carrier fit'
"PASS SUITE - $script:n assertions; 33 EXECUTED CASES; SHIPPED_ANCESTRY; ZERO_PROVIDER; ZERO_WRITES; CORE=$core"
