[CmdletBinding()]param(
 [Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$ExpectedCoreDigest,
 [Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$VerificationCapsulePath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$script:n=0
function A([bool]$ok,[string]$m){if(-not$ok){throw "ASSERTION FAILED: $m"};$script:n++}
function H([string]$text){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.UTF8Encoding]::new($false).GetBytes($text)))}
function K($o,[string]$keys,[string]$m){A ((@($o.PSObject.Properties.Name)-join',')-ceq$keys) $m}
function S([string]$v){$v-cmatch'^[A-F0-9]{64}$'}
$matrix=@'
{"schema":"fleet-exhausted-model-failback-controls.v9","candidate":"opus-model-failback-r10","authority":"ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX","capacity_max_age_seconds":300,"hard_ceiling":100,"execution":{"common":{"effort":"max","turns":12,"wall_seconds":900,"tools":["Read","StructuredOutput"],"result":"route-review-result.v1"},"fable":{"model":"claude-fable-5","role":"coordinator"},"opus":{"model":"claude-opus-5","role":"executor"},"sonnet":{"model":"claude-sonnet-5","role":"verifier"}},"assertions":["INIT_MODEL_EXACT","ROUTE_AND_SESSION_EXACT","TERMINAL_REASON_API_ERROR","HTTP_STATUS_429","EXACTLY_ONE_TURN","EXACT_MODEL_SCOPED_RESULT_TEXT","ASSISTANT_ERROR_RATE_LIMIT","ZERO_REVIEW_INPUT_TOKENS","ZERO_REVIEW_OUTPUT_TOKENS","NO_REVIEW_VERDICT_OR_ACCEPTANCE","RATE_LIMIT_EVENTS_COMPLETE_AND_ADJUDICATED","SAME_DOMAIN_CAPACITY_FRESH_SIGNED","CAPACITY_PLUS_ACTIVE_RESERVATIONS_PLUS_CONSERVATIVE_OPUS_ESTIMATE_LTE_100_EVERY_WINDOW"],"cases":[
{"id":"positive_exact_fable_exhaustion","m":"none","e":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","w":0,"p":0},
{"id":"wrong_or_alias_fable_model","m":"model","e":"HOLD_MODEL_IDENTITY","w":0,"p":0},
{"id":"generic_429_without_exact_fable_text","m":"text","e":"HOLD_EXHAUSTION_AMBIGUOUS","w":0,"p":0},
{"id":"assistant_error_missing_or_different","m":"error","e":"HOLD_TERMINAL_EVIDENCE","w":0,"p":0},
{"id":"nonterminal_or_multiturn_result","m":"terminal","e":"HOLD_TERMINAL_IDENTITY","w":0,"p":0},
{"id":"verdict_or_acceptance_present","m":"credit","e":"HOLD_CREDIT_CONFLICT","w":0,"p":0},
{"id":"nonzero_fable_review_tokens","m":"tokens","e":"HOLD_NOT_ZERO_CREDIT_EXHAUSTION","w":0,"p":0},
{"id":"rate_limit_event_omitted","m":"event","e":"HOLD_CLASSIFIER_INCOMPLETE","w":0,"p":0},
{"id":"base_window_rejected","m":"base","e":"HOLD_ACCOUNT_OR_WINDOW_EXHAUSTION","w":0,"p":0},
{"id":"overage_only_rejected_with_allowed_base_below_100","m":"allowed","e":"CONTINUE_TO_OTHER_GATES","w":0,"p":0},
{"id":"overage_only_rejected_without_base_event_with_exact_model_evidence_and_signed_base_below_100","m":"omitted","e":"CONTINUE_TO_OTHER_GATES","w":0,"p":0},
{"id":"overage_only_rejected_without_base_event_or_fresh_signed_corroboration","m":"unsigned","e":"HOLD_CLASSIFIER_AMBIGUOUS","w":0,"p":0},
{"id":"contradictory_or_unenumerated_rate_limit_event","m":"unknown","e":"HOLD_CLASSIFIER_AMBIGUOUS","w":0,"p":0},
{"id":"stale_capacity","m":"stale","e":"HOLD_CAPACITY_EVIDENCE","w":0,"p":0},
{"id":"unsigned_capacity","m":"signature","e":"HOLD_CAPACITY_EVIDENCE","w":0,"p":0},
{"id":"cross_domain_capacity","m":"cross_domain","e":"HOLD_CAPACITY_EVIDENCE","w":0,"p":0},
{"id":"same_domain_successor_capacity","m":"same_domain","e":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","w":0,"p":0},
{"id":"hard_ceiling_sum_exactly_100","m":"eq100","e":"ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION","w":0,"p":0},
{"id":"hard_ceiling_sum_above_100","m":"gt100","e":"HOLD_HARD_CEILING","w":0,"p":0},
{"id":"core_subject_reordered","m":"order","e":"HOLD_CORE_SUBJECT_DIGEST","w":0,"p":0},
{"id":"core_subject_replaced","m":"replace","e":"HOLD_CORE_SUBJECT_DIGEST","w":0,"p":0},
{"id":"core_digest_row_mutated","m":"core_mutated","e":"HOLD_CORE_SUBJECT_DIGEST","w":0,"p":0},
{"id":"execution_contract_effort_drift","m":"effort","e":"HOLD_EXECUTION_CONTRACT","w":0,"p":0},
{"id":"execution_contract_turn_or_wall_drift","m":"bounds","e":"HOLD_EXECUTION_CONTRACT","w":0,"p":0},
{"id":"execution_contract_model_role_or_tools_drift","m":"identity","e":"HOLD_EXECUTION_CONTRACT","w":0,"p":0},
{"id":"assertion_map_count_mismatch","m":"map","e":"HOLD_ASSERTION_MAP","w":0,"p":0},
{"id":"open_gate","m":"gate","e":"HOLD_OPEN_GATE","w":0,"p":0},
{"id":"live_provider_lease_or_concurrent_transaction","m":"overlap","e":"HOLD_OVERLAP","w":0,"p":0},
{"id":"unconsumed_canary","m":"unconsumed","e":"HOLD_UNCONSUMED_CANARY","w":0,"p":0},
{"id":"consumed_canary_not_authority","m":"consumed","e":"CONTINUE_TO_LATER_GATES_WITH_ZERO_ADMISSION_AUTHORITY","w":0,"p":0},
{"id":"account_domain_rotation_failure","m":"rotation","e":"ROLLED_BACK_AND_HOLD","w":0,"p":0},
{"id":"malformed_structured_output","m":"malformed","e":"HOLD_MALFORMED_OUTPUT","w":0,"p":0},
{"id":"continuation_capsule_missing_stale_or_unbound","m":"capsule","e":"HOLD_CONTINUATION_CAPSULE","w":0,"p":0},
{"id":"terminal_fable_carrier_replay","m":"replay","e":"HOLD_TERMINAL_ROUTE_REPLAY","w":0,"p":0}],"credit":"NEXT_GATE_ONLY_ZERO_AUTHORITY"}
'@
function E([string]$m){
 $x=[ordered]@{model=1;text=1;error=1;terminal=1;credit=0;tokens=0;event='allowed';fresh=1;signed=1;fd='a';cd='a';u5=14;u7=88;r5=0;r7=0;e5=5;e7=5;core=1;execution=1;map=1;gate='closed';overlap=0;canary='none';rotation=1;output=1;capsule=1;replay=0}
 switch($m){model{$x.model=0}text{$x.text=0}error{$x.error=0}terminal{$x.terminal=0}credit{$x.credit=1}tokens{$x.tokens=1}event{$x.event='missing'}base{$x.event='base'}allowed{$x.event='allowed'}omitted{$x.event='omitted'}unsigned{$x.event='uncorroborated'}unknown{$x.event='unknown'}stale{$x.fresh=0}signature{$x.signed=0}cross_domain{$x.cd='b'}same_domain{$x.fd='b';$x.cd='b'}eq100{$x.u5=90;$x.r5=5;$x.e5=5}gt100{$x.u5=91;$x.r5=5;$x.e5=5}order{$x.core=0}replace{$x.core=0}core_mutated{$x.core=0}effort{$x.execution=0}bounds{$x.execution=0}identity{$x.execution=0}map{$x.map=0}gate{$x.gate='open'}overlap{$x.overlap=1}unconsumed{$x.canary='unconsumed'}consumed{$x.canary='consumed'}rotation{$x.rotation=0}malformed{$x.output=0}capsule{$x.capsule=0}replay{$x.replay=1}none{}default{throw "unknown mutation $m"}}
 if(-not$x.model){return'HOLD_MODEL_IDENTITY'};if(-not$x.text){return'HOLD_EXHAUSTION_AMBIGUOUS'};if(-not$x.error){return'HOLD_TERMINAL_EVIDENCE'};if(-not$x.terminal){return'HOLD_TERMINAL_IDENTITY'};if($x.credit){return'HOLD_CREDIT_CONFLICT'};if($x.tokens){return'HOLD_NOT_ZERO_CREDIT_EXHAUSTION'}
 if($x.event-ceq'missing'){return'HOLD_CLASSIFIER_INCOMPLETE'};if($x.event-ceq'base'){return'HOLD_ACCOUNT_OR_WINDOW_EXHAUSTION'};if($x.event-in@('uncorroborated','unknown')){return'HOLD_CLASSIFIER_AMBIGUOUS'};if(-not$x.fresh-or-not$x.signed-or$x.fd-cne$x.cd){return'HOLD_CAPACITY_EVIDENCE'}
 if(($x.u5+$x.r5+$x.e5)-gt100-or($x.u7+$x.r7+$x.e7)-gt100){return'HOLD_HARD_CEILING'};if(-not$x.core){return'HOLD_CORE_SUBJECT_DIGEST'};if(-not$x.execution){return'HOLD_EXECUTION_CONTRACT'};if(-not$x.map){return'HOLD_ASSERTION_MAP'};if($x.gate-cne'closed'){return'HOLD_OPEN_GATE'};if($x.overlap){return'HOLD_OVERLAP'};if($x.canary-ceq'unconsumed'){return'HOLD_UNCONSUMED_CANARY'};if(-not$x.rotation){return'ROLLED_BACK_AND_HOLD'};if(-not$x.output){return'HOLD_MALFORMED_OUTPUT'};if(-not$x.capsule){return'HOLD_CONTINUATION_CAPSULE'};if($x.replay){return'HOLD_TERMINAL_ROUTE_REPLAY'}
 if($x.canary-ceq'consumed'){return'CONTINUE_TO_LATER_GATES_WITH_ZERO_ADMISSION_AUTHORITY'};if($m-in@('allowed','omitted')){return'CONTINUE_TO_OTHER_GATES'};return'ELIGIBLE_FOR_ORDINARY_OPUS_ADMISSION_EVALUATION'
}
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$s=$matrix|ConvertFrom-Json -Depth 20
K $s 'schema,candidate,authority,capacity_max_age_seconds,hard_ceiling,execution,assertions,cases,credit' 'matrix keys';A ($s.schema-ceq'fleet-exhausted-model-failback-controls.v9'-and$s.candidate-ceq'opus-model-failback-r10') 'matrix identity';A ($s.capacity_max_age_seconds-eq300-and$s.hard_ceiling-eq100) 'limits';A ($s.assertions.Count-eq13-and@($s.assertions|Sort-Object -Unique).Count-eq13) 'assertions';A ($s.cases.Count-eq34-and@($s.cases.id|Sort-Object -Unique).Count-eq34) 'cases'
A ($s.execution.common.effort-ceq'max'-and$s.execution.common.turns-eq12-and$s.execution.common.wall_seconds-eq900) 'bounds';A ((@($s.execution.common.tools)-join',')-ceq'Read,StructuredOutput'-and$s.execution.common.result-ceq'route-review-result.v1') 'tools/result';A ($s.execution.fable.model-ceq'claude-fable-5'-and$s.execution.opus.model-ceq'claude-opus-5'-and$s.execution.sonnet.model-ceq'claude-sonnet-5') 'models'
foreach($c in $s.cases){K $c 'id,m,e,w,p' "case keys $($c.id)";A ($c.w-eq0-and$c.p-eq0) "zero authority $($c.id)";A ((E $c.m)-ceq$c.e) "executed $($c.id)"}
$bundlePath=Join-Path $repo 'receipts\opus-model-failback-r10-evidence-bundle-20260825.json';$bundleRaw=[IO.File]::ReadAllText($bundlePath);$b=$bundleRaw|ConvertFrom-Json -Depth 20
K $b 'schema,closed_keys,created_at_utc,generator,review_history,validated_extracts,r9_findings,r10_repairs,contract,authority' 'bundle keys';A ($b.schema-ceq'fleet-opus-model-failback-evidence-bundle.v5'-and$b.closed_keys) 'bundle identity';A ($b.r9_findings.Count-eq11-and$b.r10_repairs.Count-eq11) 'finding closure';A ($b.contract.hidden_reads-eq0-and$b.contract.executed_cases-eq34-and$b.contract.repeat_passes-eq3) 'bundle contract';A ($b.validated_extracts.r9.opus_verdict-ceq'REVISE'-and$b.validated_extracts.r9.opus_actionable-eq11-and$b.validated_extracts.r9.serial_acceptance-ceq'ZERO') 'r9 adverse';A ($b.validated_extracts.r8.opus_verdict-ceq'ACCEPT'-and$b.validated_extracts.r8.sonnet_verdict-ceq'REVISE') 'r8 history'
$candidatePath=Join-Path $repo 'ruling-candidates\opus-model-failback-r1.md';$candidate=[IO.File]::ReadAllText($candidatePath);A ($candidate.StartsWith('# Ruling candidate: exhausted-model failback to Opus R10')) 'candidate title';foreach($term in @('verifier may read only the three core subjects and that capsule','age is derived, never rounded or self-published','signed-capacity source/signer','consumed carrier hash','R10 repairs all eleven findings')){A ($candidate.Contains($term)) "candidate $term"}
$rels=@('ruling-candidates/opus-model-failback-r1.md','tests/test-opus-model-failback-r3-controls.ps1','receipts/opus-model-failback-r10-evidence-bundle-20260825.json');$rows=[Collections.Generic.List[object]]::new();foreach($r in $rels){$p=Join-Path $repo ($r-replace'/',[IO.Path]::DirectorySeparatorChar);$i=Get-Item -LiteralPath $p;$rows.Add([ordered]@{path=$r;bytes=[int64]$i.Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash})};$core=H ($rows|ConvertTo-Json -Compress -Depth 5);A ($core-ceq$ExpectedCoreDigest.ToUpperInvariant()) 'external core digest';$mut=@($rows|ForEach-Object{[ordered]@{path=$_.path;bytes=$_.bytes;sha256=$_.sha256}});$mut[0].sha256='0'*64;A ((H ($mut|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row mutation';A ((H (@($rows[1],$rows[0],$rows[2])|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row order'
$capFile=[IO.Path]::GetFullPath($VerificationCapsulePath);$capRaw=[IO.File]::ReadAllText($capFile);$cap=$capRaw|ConvertFrom-Json -Depth 20
K $cap 'schema,generation,lane,binding,core,git,local,prior,capacity,terminal,authority' 'capsule keys';A ($cap.schema-ceq'fleet-opus-model-failback-verification-capsule.v2'-and$cap.generation-ceq'opus-model-failback-r10'-and$cap.lane-in@('fable','opus','sonnet')) 'capsule identity'
K $cap.binding 'ancestry_packet_sha256,route_id,session_id,model,core_subjects_sha256' 'binding keys';A ((S $cap.binding.ancestry_packet_sha256)-and(S $cap.binding.core_subjects_sha256)-and$cap.binding.session_id-cmatch'^[0-9a-f-]{36}$'-and$cap.binding.route_id-cmatch'^fleet-opus-model-failback-r(9|10)-') 'ancestry binding';if($cap.lane-ceq'fable'){A ($cap.binding.ancestry_packet_sha256-ceq$b.validated_extracts.r9.opus_packet_sha256-and$cap.binding.route_id-ceq$b.validated_extracts.r9.opus_route_id-and$cap.binding.session_id-ceq$b.validated_extracts.r9.opus_session_id-and$cap.binding.model-ceq$b.validated_extracts.r9.opus_model-and$cap.binding.core_subjects_sha256-ceq$b.validated_extracts.r9.core_sha256) 'r9 to r10 binding'}else{A ($cap.binding.model-in@('claude-fable-5','claude-opus-5')) 'serial ancestry model'}
K $cap.core 'algorithm,sha256,subject_count,subject_bytes' 'core keys';$coreBytes=($rows|Measure-Object bytes -Sum).Sum;A ($cap.core.algorithm-ceq'SHA256_CANONICAL_CLOSED_KEY_ORDERED_ROWS_V1'-and$cap.core.sha256-ceq$core-and$cap.core.subject_count-eq3-and$cap.core.subject_bytes-eq$coreBytes) 'current core'
K $cap.git 'commit,tree,branch,commit_type,tree_type,head_matches,tree_matches,status_clean' 'git keys';A ((S $cap.git.commit)-and(S $cap.git.tree)-and$cap.git.commit_type-ceq'commit'-and$cap.git.tree_type-ceq'tree'-and$cap.git.head_matches-and$cap.git.tree_matches-and$cap.git.status_clean-and$cap.git.branch-ceq'codex/opus-model-failback-r1') 'git attestation'
K $cap.local 'executable_path,executable_sha256,command,repeat_passes,assertions,executed_cases,output_sha256' 'local keys';$selfHash=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;A ($cap.local.executable_path-ceq'tests/test-opus-model-failback-r3-controls.ps1'-and$cap.local.executable_sha256-ceq$selfHash-and$cap.local.repeat_passes-eq3-and$cap.local.executed_cases-eq34-and$cap.local.assertions-gt0) 'local execution';A ($cap.local.output_sha256.Count-eq3-and@($cap.local.output_sha256|Sort-Object -Unique).Count-eq1-and(S $cap.local.output_sha256[0])) 'identical outputs'
K $cap.prior 'bundle_sha256,bundle_schema,r9_verdict,r9_actionable,r8_sonnet_verdict,r8_sonnet_actionable,validated' 'prior keys';A ($cap.prior.bundle_sha256-ceq(H $bundleRaw)-and$cap.prior.bundle_schema-ceq$b.schema-and$cap.prior.r9_verdict-ceq'REVISE'-and$cap.prior.r9_actionable-eq11-and$cap.prior.r8_sonnet_verdict-ceq'REVISE'-and$cap.prior.r8_sonnet_actionable-eq3-and$cap.prior.validated) 'prior extracts'
K $cap.capacity 'source,signer,signature,ledger_sha256,account_domain,observed_at_utc,capsule_created_at_utc,utilization,active_reservations,estimate,sum,hard_ceiling,no_overlap' 'capacity keys';A ($cap.capacity.source-ceq'anthropic-oauth-usage-v1'-and$cap.capacity.signer-ceq'anthropic-oauth-usage-v1'-and$cap.capacity.signature-cmatch'^hmac-sha256:[a-f0-9]{64}$'-and(S $cap.capacity.ledger_sha256)-and$cap.capacity.account_domain-cmatch'^anthropic-org/hmac-sha256:[a-f0-9]{64}$') 'signed capacity';$age=([datetime]$cap.capacity.capsule_created_at_utc-[datetime]$cap.capacity.observed_at_utc).TotalSeconds;A ($age-ge0-and$age-le$s.capacity_max_age_seconds) 'derived exact age';A ($cap.capacity.sum.five_hour-eq($cap.capacity.utilization.five_hour+$cap.capacity.active_reservations.five_hour+$cap.capacity.estimate.five_hour)-and$cap.capacity.sum.seven_day-eq($cap.capacity.utilization.seven_day+$cap.capacity.active_reservations.seven_day+$cap.capacity.estimate.seven_day)) 'capacity sums';A ($cap.capacity.sum.five_hour-le$cap.capacity.hard_ceiling-and$cap.capacity.sum.seven_day-le$cap.capacity.hard_ceiling-and$cap.capacity.hard_ceiling-eq100-and$cap.capacity.no_overlap) 'capacity ceiling'
K $cap.terminal 'lane,consumed_packet_sha256,terminal_packet_sha256,terminal_receipt_sha256,terminal_lease_sha256,close_receipt_sha256,closed_before_clear' 'terminal keys';foreach($k in @('consumed_packet_sha256','terminal_packet_sha256','terminal_receipt_sha256','terminal_lease_sha256','close_receipt_sha256')){A (S $cap.terminal.$k) "terminal $k"};A ($cap.terminal.lane-ceq'fable'-and$cap.terminal.closed_before_clear-and$cap.terminal.consumed_packet_sha256-ceq$b.validated_extracts.r9.fable_packet_sha256-and$cap.terminal.terminal_packet_sha256-ceq$b.validated_extracts.r9.fable_terminal_carrier_sha256-and$cap.terminal.terminal_receipt_sha256-ceq$b.validated_extracts.r9.fable_exhaustion_receipt_sha256-and$cap.terminal.terminal_lease_sha256-ceq$b.validated_extracts.r9.fable_terminal_lease_sha256-and$cap.terminal.close_receipt_sha256-ceq$b.validated_extracts.r9.fable_hold_clear_sha256) 'terminal transition'
A ($cap.authority-ceq'READ_ONLY_EVIDENCE_ZERO_PROVIDER_ZERO_ACCEPTANCE_ZERO_ADOPTION') 'authority';$capBytes=(Get-Item -LiteralPath $capFile).Length;A ($rows.Count+1-le4-and$capBytes-le24576-and$coreBytes+$capBytes-le32768) 'r2.1 fit'
"PASS SUITE - $script:n assertions; 34 EXECUTED CASES; VERIFIED_CAPSULE_V2; ZERO_PROVIDER; ZERO_WRITES; CORE=$core"
