[CmdletBinding()]param(
 [Parameter(Mandatory)][ValidatePattern('^[A-Fa-f0-9]{64}$')][string]$ExpectedCoreDigest,
 [Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$VerificationCapsulePath,
 [Parameter(Mandatory)][ValidateScript({Test-Path -LiteralPath $_ -PathType Leaf})][string]$IssuingPacketPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$script:n=0
function A([bool]$ok,[string]$m){if(-not$ok){throw "ASSERTION FAILED [$script:n]: $m"};$script:n++}
function Q([string]$text){[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.UTF8Encoding]::new($false).GetBytes($text)))}
function K($o,[string]$keys,[string]$m){A ((@($o.PSObject.Properties.Name)-join',')-ceq$keys) $m}
function S([string]$v){$v-cmatch'^[A-F0-9]{64}$'}
$matrix=@'
{"schema":"fleet-exhausted-model-failback-controls.v19","candidate":"opus-model-failback-r21","authority":"ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX","capacity_max_age_seconds":300,"hard_ceiling":100,"execution":{"common":{"effort":"max","turns":12,"wall_seconds":900,"tools":["Read","StructuredOutput"],"result":"route-review-result.v1"},"fable":{"model":"claude-fable-5","role":"coordinator"},"opus":{"model":"claude-opus-5","role":"executor"},"sonnet":{"model":"claude-sonnet-5","role":"verifier"}},"assertions":["INIT_MODEL_EXACT","ROUTE_PACKET_SESSION_EXACT","TERMINAL_REASON_API_ERROR","HTTP_STATUS_429","EXACTLY_ONE_TURN","EXACT_MODEL_SCOPED_RESULT_TEXT","ASSISTANT_ERROR_RATE_LIMIT","ZERO_REVIEW_INPUT_TOKENS","ZERO_REVIEW_OUTPUT_TOKENS","NO_REVIEW_VERDICT_OR_ACCEPTANCE","RATE_LIMIT_EVENTS_COMPLETE_AND_ADJUDICATED","SAME_DOMAIN_CAPACITY_FRESH_SIGNED","CAPACITY_PLUS_ACTIVE_RESERVATIONS_PLUS_CONSERVATIVE_OPUS_ESTIMATE_LTE_100_EVERY_WINDOW","TERMINAL_HASHES_CROSS_BOUND_CLOSE_BEFORE_CLEAR"],"cases":[["exact","none","ELIG"],["wrong_model","model","MODEL"],["generic_429","text","AMBIG"],["error_missing","error","TERM"],["nonterminal","terminal","IDENT"],["verdict_present","credit","CREDIT"],["nonzero_tokens","tokens","TOKENS"],["event_missing","event","CLASS"],["base_rejected","base","ACCOUNT"],["overage_allowed","allowed","OTHER"],["overage_omitted","omitted","OTHER"],["overage_uncorroborated","unsigned","CLASS"],["event_unknown","unknown","CLASS"],["stale_capacity","stale","CAP"],["unsigned_capacity","signature","CAP"],["cross_domain","cross_domain","CAP"],["same_domain_successor","same_domain","ELIG"],["sum_eq100","eq100","ELIG"],["sum_gt100","gt100","CEIL"],["core_reorder","order","CORE"],["core_replace","replace","CORE"],["core_mutated","core_mutated","CORE"],["effort_drift","effort","EXEC"],["bounds_drift","bounds","EXEC"],["identity_drift","identity","EXEC"],["assertion_map","map","MAP"],["open_gate","gate","GATE"],["overlap","overlap","OVERLAP"],["unconsumed_canary","unconsumed","CANARY"],["consumed_canary","consumed","LATER"],["rotation_failure","rotation","ROLLBACK"],["malformed_output","malformed","OUTPUT"],["capsule_unbound","capsule","CAPSULE"],["terminal_fable_carrier_replay","terminal_fable_carrier_replay","REPLAY"],["terminal_binding","terminal_bind","BIND"]],"credit":"NEXT_GATE_ONLY_ZERO_AUTHORITY"}
'@
function E([string]$m){
 $x=[ordered]@{model=1;text=1;assistantError=1;terminalReason=1;credit=0;tokens=0;event='allowed';fresh=1;signed=1;fd='a';cd='a';u5=14;u7=88;r5=0;r7=0;e5=5;e7=5;coreOrder=1;coreReplace=1;coreBytes=1;effortExact=1;boundsExact=1;identityExact=1;map=1;gate='closed';overlap=0;canary='none';rotation=1;output=1;capsule=1;replay=0;packetBind=1;sessionBind=1;terminalBind=1;closeBeforeClear=1}
 switch($m){model{$x.model=0}text{$x.text=0}error{$x.assistantError=0}terminal{$x.terminalReason=0}credit{$x.credit=1}tokens{$x.tokens=1}event{$x.event='missing'}base{$x.event='base'}allowed{$x.event='allowed'}omitted{$x.event='omitted'}unsigned{$x.event='uncorroborated'}unknown{$x.event='unknown'}stale{$x.fresh=0}signature{$x.signed=0}cross_domain{$x.cd='b'}same_domain{$x.fd='b';$x.cd='b'}eq100{$x.u5=90;$x.r5=5;$x.e5=5}gt100{$x.u5=91;$x.r5=5;$x.e5=5}order{$x.coreOrder=0}replace{$x.coreReplace=0}core_mutated{$x.coreBytes=0}effort{$x.effortExact=0}bounds{$x.boundsExact=0}identity{$x.identityExact=0}map{$x.map=0}gate{$x.gate='open'}overlap{$x.overlap=1}unconsumed{$x.canary='unconsumed'}consumed{$x.canary='consumed'}rotation{$x.rotation=0}malformed{$x.output=0}capsule{$x.capsule=0}terminal_fable_carrier_replay{$x.replay=1}terminal_bind{$x.packetBind=0;$x.sessionBind=0;$x.terminalBind=0;$x.closeBeforeClear=0}none{}default{throw "unknown mutation $m"}}
 if(-not$x.model){return 'MODEL'};if(-not$x.text){return 'AMBIG'};if(-not$x.assistantError){return 'TERM'};if(-not$x.terminalReason){return 'IDENT'};if($x.credit){return 'CREDIT'};if($x.tokens){return 'TOKENS'}
 if($x.event-ceq'missing'){return 'CLASS'};if($x.event-ceq'base'){return 'ACCOUNT'};if($x.event-in@('uncorroborated','unknown')){return 'CLASS'};if(-not$x.fresh-or-not$x.signed-or$x.fd-cne$x.cd){return 'CAP'}
 if(($x.u5+$x.r5+$x.e5)-gt100-or($x.u7+$x.r7+$x.e7)-gt100){return 'CEIL'};if(-not$x.coreOrder-or-not$x.coreReplace-or-not$x.coreBytes){return 'CORE'};if(-not$x.effortExact-or-not$x.boundsExact-or-not$x.identityExact){return 'EXEC'};if(-not$x.map){return 'MAP'};if($x.gate-cne'closed'){return 'GATE'};if($x.overlap){return 'OVERLAP'};if($x.canary-ceq'unconsumed'){return 'CANARY'};if(-not$x.rotation){return 'ROLLBACK'};if(-not$x.output){return 'OUTPUT'};if(-not$x.capsule){return 'CAPSULE'};if($x.replay){return 'REPLAY'}
 if(-not$x.packetBind-or-not$x.sessionBind-or-not$x.terminalBind-or-not$x.closeBeforeClear){return 'BIND'};if($x.canary-ceq'consumed'){return 'LATER'};if($m-in@('allowed','omitted')){return 'OTHER'};return 'ELIG'
}
$repo=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'));$s=$matrix|ConvertFrom-Json -Depth 20
K $s 'schema,candidate,authority,capacity_max_age_seconds,hard_ceiling,execution,assertions,cases,credit' 'matrix keys';A ($s.schema-ceq'fleet-exhausted-model-failback-controls.v19'-and$s.candidate-ceq'opus-model-failback-r21') 'matrix identity';A ($s.capacity_max_age_seconds-eq300-and$s.hard_ceiling-eq100) 'limits';A ($s.assertions.Count-eq14-and@($s.assertions|Sort-Object -Unique).Count-eq14) 'assertions';A ($s.cases.Count-eq35-and@($s.cases|ForEach-Object{$_[0]}|Sort-Object -Unique).Count-eq35) '35 unique cases'
A ($s.execution.common.effort-ceq'max'-and$s.execution.common.turns-eq12-and$s.execution.common.wall_seconds-eq900) 'bounds';A ((@($s.execution.common.tools)-join',')-ceq'Read,StructuredOutput'-and$s.execution.common.result-ceq'route-review-result.v1') 'tools/result';A ($s.execution.fable.model-ceq'claude-fable-5'-and$s.execution.opus.model-ceq'claude-opus-5'-and$s.execution.sonnet.model-ceq'claude-sonnet-5') 'models';A ($s.authority-ceq'ZERO_AUTHORITY_EXECUTED_REPRODUCTION_MATRIX') 'matrix authority'
foreach($c in $s.cases){A ($c.Count-eq3-and(E $c[1])-ceq$c[2]) "executed case $($c[0])"}
$bundlePath=Join-Path $repo 'receipts\opus-model-failback-r21-evidence-bundle-20260826.json';$bundleRaw=[IO.File]::ReadAllText($bundlePath);$b=$bundleRaw|ConvertFrom-Json -Depth 20 -DateKind String
K $b 'schema,closed_keys,created_at_utc,prior_r20,current_fable,r20_opus,terminal_carrier,contract,authority' 'bundle keys';A ($b.schema-ceq'fleet-opus-model-failback-evidence-bundle.v16'-and$b.closed_keys) 'bundle identity'
K $b.prior_r20 'commit,tree,core_sha256,bundle_sha256,test_sha256' 'r20 keys';A ($b.prior_r20.commit-ceq'4A98331F1755633AB8A3B74A1A5C110692F59D95'-and$b.prior_r20.tree-ceq'23B4B39F03FF6CD4FB851D685B7B926CF473462A'-and$b.prior_r20.core_sha256-ceq'7B40BE621118615FAAF9313CA3254EE840AE815ADFCD6569ACBC6353F9079453') 'r20 ancestry'
$f=$b.current_fable;K $f 'route_id,packet_sha256,session_id,model,turns,status,terminal_reason,assistant_error,result,input_tokens,output_tokens,verdict_present,credit,account_domain,exhaustion_receipt_sha256,terminal_packet_sha256,terminal_lease_sha256,hold_clear_sha256,artifact_sha256' 'fable keys';A ($f.route_id-ceq'fleet-opus-model-failback-r20-fable-core-r1'-and$f.packet_sha256-ceq'D80D01AD7F56ADB11DDDD2D4ABB3A2FAA6FEB61B18AC02124DD18DD0B5B82D32'-and$f.session_id-ceq'029fda1a-83bd-4463-8550-64dbe3e877ad') 'exact r20 fable route packet session';A ($f.model-ceq'claude-fable-5'-and$f.turns-eq1-and$f.status-eq429-and$f.terminal_reason-ceq'api_error'-and$f.assistant_error-ceq'rate_limit'-and$f.result-ceq"You've reached your Fable 5 limit. Run /usage-credits to continue or switch models with /model."-and$f.input_tokens-eq0-and$f.output_tokens-eq0-and-not$f.verdict_present-and$f.credit-ceq'ZERO') 'exact r20 exhaustion discriminators';A ((S $f.exhaustion_receipt_sha256)-and(S $f.terminal_packet_sha256)-and(S $f.terminal_lease_sha256)-and(S $f.hold_clear_sha256)-and(S $f.artifact_sha256)) 'fable terminal hashes'
$o=$b.r20_opus;K $o 'route_id,packet_sha256,session_id,model,effort,role,turns,output_tokens,verdict,actionable_findings,consumption_receipt_sha256,artifact_sha256,review_result_sha256,terminal_packet_sha256,terminal_lease_sha256' 'opus keys';A ($o.route_id-ceq'fleet-opus-model-failback-r20-opus-after-fable-exhaustion'-and$o.packet_sha256-ceq'60C6E02A921CBEEB92142D481B633F215FA4F76C4FE296F27D86C37463733D45'-and$o.session_id-ceq'ad9c0221-fc53-4e5b-9fc9-72e50c0dc5be') 'exact r20 opus';A ($o.model-ceq'claude-opus-5'-and$o.effort-ceq'max'-and$o.role-ceq'executor'-and$o.turns-eq7-and$o.output_tokens-eq34814-and$o.verdict-ceq'ACCEPT'-and$o.actionable_findings-eq4) 'opus accept with forward findings';A ((S $o.consumption_receipt_sha256)-and(S $o.artifact_sha256)-and(S $o.review_result_sha256)-and(S $o.terminal_packet_sha256)-and(S $o.terminal_lease_sha256)) 'opus receipts';A ($b.contract.cases-eq35-and$b.contract.repeats-eq3-and$b.contract.max_age-eq300-and$b.contract.ceiling-eq100-and$b.contract.subject_count-eq4-and$b.contract.hidden_reads-eq0-and$b.contract.capsule_schema-ceq'fleet-opus-model-failback-verification-capsule.v9') 'contract'
$candidatePath=Join-Path $repo 'ruling-candidates\opus-model-failback-r1.md';$candidate=[IO.File]::ReadAllText($candidatePath);A ($candidate.StartsWith('# Ruling candidate: exhausted-model failback to Opus R21')) 'candidate title';foreach($term in @('all three on-lane core rows','terminal_reason=api_error','assistant_error=rate_limit','exact terminal carrier bytes','independent core mutations','independent execution mutations','34,814 output tokens','Sonnet must ACCEPT')){A ($candidate.Contains($term)) "candidate $term"}
$rels=@('ruling-candidates/opus-model-failback-r1.md','tests/test-opus-model-failback-r6-controls.ps1','receipts/opus-model-failback-r21-evidence-bundle-20260826.json');$rows=[Collections.Generic.List[object]]::new();foreach($r in $rels){$p=Join-Path $repo ($r-replace'/',[IO.Path]::DirectorySeparatorChar);$i=Get-Item -LiteralPath $p;$rows.Add([ordered]@{path=$r;bytes=[int64]$i.Length;sha256=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash})};$core=Q ($rows|ConvertTo-Json -Compress -Depth 5);A ($core-ceq$ExpectedCoreDigest.ToUpperInvariant()) 'external core digest';A (@($rows|Where-Object{$_.bytes-gt24576}).Count-eq0) 'subject fit';$mut=@($rows|ForEach-Object{[ordered]@{path=$_.path;bytes=$_.bytes;sha256=$_.sha256}});$mut[0].sha256='0'*64;A ((Q ($mut|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row mutation';A ((Q (@($rows[1],$rows[0],$rows[2])|ConvertTo-Json -Compress -Depth 5))-cne$core) 'row order'
$capFile=[IO.Path]::GetFullPath($VerificationCapsulePath);$capRaw=[IO.File]::ReadAllText($capFile);$cap=$capRaw|ConvertFrom-Json -Depth 20 -DateKind String;K $cap 'schema,generation,lane,packet,ancestry,core,git,local,prior,current_fable,capacity,terminal,terminal_carrier,authority' 'capsule keys';A ($cap.schema-ceq'fleet-opus-model-failback-verification-capsule.v9'-and$cap.generation-ceq'opus-model-failback-r21'-and$cap.lane-in@('fable','opus','sonnet')) 'capsule identity'
K $cap.packet 'route_id,issued_at_utc,expires_at_utc' 'capsule packet keys';$packetFile=[IO.Path]::GetFullPath($IssuingPacketPath);$packetRaw=[IO.File]::ReadAllText($packetFile);$packet=$packetRaw|ConvertFrom-Json -Depth 20 -DateKind String;K $packet 'schema,route_id,lane,role,authority,objective,issued_at_utc,expires_at_utc,actionable_work,no_subagents,no_lane_reopen,subjects,result_contract' 'packet keys';$bad=@($packet.subjects|Where-Object{(@($_.PSObject.Properties.Name)-join',')-cne'path,bytes,sha256'-or$_.path-isnot[string]-or$_.sha256-isnot[string]-or[Type]::GetTypeCode($_.bytes.GetType())-notin@([TypeCode]::SByte,[TypeCode]::Byte,[TypeCode]::Int16,[TypeCode]::UInt16,[TypeCode]::Int32,[TypeCode]::UInt32,[TypeCode]::Int64,[TypeCode]::UInt64)});A ($packet.schema-is[string]-and$packet.authority-is[string]-and$packet.result_contract-is[string]-and$packet.actionable_work-is[bool]-and$packet.no_subagents-is[bool]-and$packet.no_lane_reopen-is[bool]-and$packet.subjects-is[array]-and$bad.Count-eq0) 'native packet types';A ($packet.schema-ceq'dng-headless-route.v1'-and$packet.authority-ceq'read-only-review'-and$packet.result_contract-ceq'route-review-result.v1'-and$packet.route_id-ceq$cap.packet.route_id-and$packet.issued_at_utc-ceq$cap.packet.issued_at_utc-and$packet.expires_at_utc-ceq$cap.packet.expires_at_utc-and$packet.lane-ceq$cap.lane-and$packet.actionable_work-and$packet.no_subagents-and$packet.no_lane_reopen) 'packet binding';$capRow=@($packet.subjects|Where-Object{[IO.Path]::GetFullPath($_.path)-ceq$capFile});A ($capRow.Count-eq1-and$capRow[0].bytes-eq(Get-Item $capFile).Length-and$capRow[0].sha256-ceq(Q $capRaw)) 'capsule row';for($i=0;$i-lt$rows.Count;$i++){$pr=$packet.subjects[$i];$ep=[IO.Path]::GetFullPath((Join-Path $repo ($rows[$i].path-replace'/',[IO.Path]::DirectorySeparatorChar)));A ([IO.Path]::GetFullPath([string]$pr.path)-ceq$ep-and[int64]$pr.bytes-eq[int64]$rows[$i].bytes-and[string]$pr.sha256-ceq[string]$rows[$i].sha256) "exact on-lane core row $i"}
K $cap.ancestry 'consumed_packet_sha256,exhaustion_receipt_sha256,route_id,session_id,model,core_sha256' 'ancestry keys';A ((S $cap.ancestry.consumed_packet_sha256)-and(S $cap.ancestry.exhaustion_receipt_sha256)-and$cap.ancestry.session_id-cmatch'^[0-9a-f-]{36}$'-and(S $cap.ancestry.core_sha256)) 'ancestry shape';A ($cap.core.format-ceq'SHA256_CANONICAL_CLOSED_KEY_ORDERED_ROWS_V1'-and$cap.core.sha256-ceq$core-and$cap.core.subject_count-eq3-and$cap.core.bytes-eq(($rows|ForEach-Object{$_.bytes}|Measure-Object -Sum).Sum)) 'core';A ($cap.git.commit-cmatch'^[A-F0-9]{40}$'-and$cap.git.tree-cmatch'^[A-F0-9]{40}$'-and$cap.git.branch-ceq'codex/opus-model-failback-r21-ratification-candidate'-and$cap.git.clean) 'git'
K $cap.prior 'bundle_sha256,bundle_schema,fable_credit,opus_verdict,opus_actionable_findings,opus_review_result_sha256,adoption_credit' 'prior keys';A ($cap.prior.bundle_sha256-ceq(Q $bundleRaw)-and$cap.prior.bundle_schema-ceq$b.schema-and$cap.prior.fable_credit-ceq'ZERO'-and$cap.prior.opus_verdict-ceq'ACCEPT'-and$cap.prior.opus_actionable_findings-eq4-and$cap.prior.opus_review_result_sha256-ceq$o.review_result_sha256-and$cap.prior.adoption_credit-ceq'ZERO') 'prior'
$cf=$cap.current_fable;K $cf 'route_id,packet_sha256,session_id,model,turns,status,terminal_reason,assistant_error,result,input_tokens,output_tokens,verdict_present,credit,account_domain,exhaustion_receipt_sha256,terminal_packet_sha256,terminal_lease_sha256,hold_clear_sha256,artifact_sha256' 'current fable keys';A ($cf.model-ceq'claude-fable-5'-and$cf.turns-eq1-and$cf.status-eq429-and$cf.terminal_reason-ceq'api_error'-and$cf.assistant_error-ceq'rate_limit'-and$cf.result-ceq"You've reached your Fable 5 limit. Run /usage-credits to continue or switch models with /model."-and$cf.input_tokens-eq0-and$cf.output_tokens-eq0-and-not$cf.verdict_present-and$cf.credit-ceq'ZERO') 'exact current fable exhaustion discriminators';A ($cap.ancestry.consumed_packet_sha256-ceq$cf.packet_sha256-and$cap.ancestry.exhaustion_receipt_sha256-ceq$cf.exhaustion_receipt_sha256-and$cap.ancestry.route_id-ceq$cf.route_id-and$cap.ancestry.session_id-ceq$cf.session_id-and$cap.ancestry.model-ceq$cf.model) 'exact ancestry cross-binding';if($cap.lane-ceq'fable'){A (($cf|ConvertTo-Json -Compress)-ceq($f|ConvertTo-Json -Compress)) 'r20 fable extract';A ($cap.ancestry.core_sha256-ceq$b.prior_r20.core_sha256) 'r20 core ancestry'}else{A ($cf.route_id-cmatch'^fleet-opus-model-failback-r21-fable-core') 'r21 fable route';A ($cap.ancestry.core_sha256-ceq$core) 'r21 core ancestry'}
K $cap.terminal 'lane,consumed_packet_sha256,exhaustion_receipt_sha256,terminal_packet_sha256,terminal_lease_sha256,hold_clear_sha256,artifact_sha256,close_before_clear' 'terminal keys';A ($cap.terminal.lane-ceq'fable'-and$cap.terminal.close_before_clear-and(S $cap.terminal.terminal_packet_sha256)-and(S $cap.terminal.terminal_lease_sha256)-and(S $cap.terminal.hold_clear_sha256)-and(S $cap.terminal.artifact_sha256)) 'terminal shape';A ($cap.terminal.consumed_packet_sha256-ceq$cap.ancestry.consumed_packet_sha256-and$cap.terminal.exhaustion_receipt_sha256-ceq$cap.ancestry.exhaustion_receipt_sha256-and$cap.terminal.terminal_packet_sha256-ceq$cf.terminal_packet_sha256-and$cap.terminal.terminal_lease_sha256-ceq$cf.terminal_lease_sha256-and$cap.terminal.hold_clear_sha256-ceq$cf.hold_clear_sha256-and$cap.terminal.artifact_sha256-ceq$cf.artifact_sha256) 'all terminal hashes cross-bound';K $cap.terminal_carrier 'canonical_json,bytes,sha256' 'terminal carrier keys';A (($cap.terminal_carrier|ConvertTo-Json -Compress)-ceq($b.terminal_carrier|ConvertTo-Json -Compress)) 'terminal carrier bundle binding';$tcRaw=[string]$cap.terminal_carrier.canonical_json;A ([Text.UTF8Encoding]::new($false).GetByteCount($tcRaw)-eq$cap.terminal_carrier.bytes-and(Q $tcRaw)-ceq$cap.terminal_carrier.sha256) 'exact terminal carrier bytes and hash';$tc=$tcRaw|ConvertFrom-Json -Depth 10 -DateKind String;K $tc 'schema,route_id,lane,role,authority,objective,issued_at_utc,expires_at_utc,actionable_work,no_subagents,no_lane_reopen,subjects,result_contract' 'terminal carrier packet keys';A ($tc.schema-ceq'dng-headless-route.v1'-and$tc.route_id-cmatch'^[A-Za-z0-9][A-Za-z0-9._-]{2,63}$'-and$tc.lane-ceq'fable'-and$tc.role-ceq'coordinator'-and$tc.authority-ceq'read-only-review'-and$tc.actionable_work-is[bool]-and-not$tc.actionable_work-and$tc.subjects-is[array]-and@($tc.subjects).Count-eq0-and$tc.result_contract-ceq'route-review-result.v1') 'derived terminal no-work semantics'
K $cap.capacity 'schema,proof,ledger_sha256,account_domain,observed_at_utc,packet_issued_at_utc,u5,u7,r5,r7,e5,e7,sum5,sum7,ceiling,assertion' 'capacity keys';A ($cap.capacity.schema-ceq'anthropic-oauth-usage-v1'-and$cap.capacity.proof-cmatch'^hmac-sha256:[a-f0-9]{64}$'-and(S $cap.capacity.ledger_sha256)-and$cap.capacity.account_domain-ceq$cf.account_domain) 'capacity proof';$age=([datetime]$packet.issued_at_utc-[datetime]$cap.capacity.observed_at_utc).TotalSeconds;A ($age-ge0-and$age-le$s.capacity_max_age_seconds-and$cap.capacity.packet_issued_at_utc-ceq$packet.issued_at_utc) 'capacity freshness';A ($cap.capacity.sum5-eq($cap.capacity.u5+$cap.capacity.r5+$cap.capacity.e5)-and$cap.capacity.sum7-eq($cap.capacity.u7+$cap.capacity.r7+$cap.capacity.e7)) 'capacity sums';A ($cap.capacity.sum5-le100-and$cap.capacity.sum7-le100-and$cap.capacity.ceiling-eq100-and$cap.capacity.assertion) 'capacity ceiling'
K $cap.local 'path,sha256,command,repeats,assertions,cases,pass_sha256' 'local keys';$selfHash=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;$expected=@{fable=108;opus=108;sonnet=108};A ($cap.local.path-ceq'tests/test-opus-model-failback-r6-controls.ps1'-and$cap.local.sha256-ceq$selfHash-and$cap.local.command-ceq'pwsh r6'-and$cap.local.repeats-eq3-and$cap.local.assertions-eq$expected[$cap.lane]-and$cap.local.cases-eq35-and(S $cap.local.pass_sha256)) "exact local assertions expected=$($expected[$cap.lane]) provided=$($cap.local.assertions)"
A ($cap.authority-ceq'READ_ONLY_EVIDENCE_ZERO_PROVIDER_ZERO_ACCEPTANCE_ZERO_ADOPTION') 'authority';$coreBytes=($rows|ForEach-Object{$_.bytes}|Measure-Object -Sum).Sum;A ($rows.Count+1-le4-and$coreBytes+(Get-Item $capFile).Length-le32768) 'r2.1 fit'
"PASS SUITE - $script:n assertions; 35 EXECUTED CASES; VERIFIED_CAPSULE_V9; ZERO_PROVIDER; ZERO_WRITES; CORE=$core"
